In [5]:
import numpy as np

np_array = np.array([5, 15, 25, 35, 45])
zeros = np.zeros(7)
ones = np.ones(6)
np_arange = np.arange(10,20)

print(np_arange)

[10 11 12 13 14 15 16 17 18 19]


In [13]:
data1 = np.array([12, 24, 36, 48, 60])
data_multiply = data1 * 2
data_add = data1 + 10
data_square = data1 ** 2
data_sqrt = np.sqrt(data1)

print(f"{data_multiply} \n{data_add} \n{data_square} \n{data_sqrt}")

[ 24  48  72  96 120] 
[22 34 46 58 70] 
[ 144  576 1296 2304 3600] 
[3.46410162 4.89897949 6.         6.92820323 7.74596669]


In [18]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
d_mean = np.mean(data)
d_min = np.min(data)
d_max = np.max(data)
d_sum = np.sum(data)

print(d_sum)

318


In [28]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0])
print(arr[-1])
print(arr[1:4])
mask = arr > 40
print(arr[mask])

15
67
[22 35 44]
[44 58 67]


In [39]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

print(matrix.shape)
print(matrix[0])
print(matrix[:,1])
m_sum = np.sum(matrix)
m_mean = np.mean(matrix)
print(m_sum)
print(m_mean)

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
